#!/bin/bash

set -e

if [ -n "$DEBUG_STARTUP" ]; then
	set -x
fi

reload() {
	pg_ctl reload
}

shutdown() {
	pg_ctl stop
}

enable_debug() {
	set -x
}

disable_debug() {
	set +x
}

trap "reload"        HUP
trap "shutdown"      TERM INT
trap "enable_debug"  USR1
trap "disable_debug" USR2

for var in PG_POSTGRES_PASSWORD PG_DATABASE; do
	if [ -z "${!var}" ]; then
		echo "Required environment variable not set: $var" >&2
		exit 1
	fi
done

PGDATA="/var/lib/postgresql/${PG_MAJOR}/${PG_CLUSTER}"
PGBIN="/usr/lib/postgresql/${PG_MAJOR}/bin"

POSTGRESQL_CONF="${PGDATA}/postgresql.conf"
PG_HBA_CONF="${PGDATA}/pg_hba.conf"

: ${BDR_NODE_NAME:=$HOSTNAME}
: ${EXTERNAL_DSN:=host=${BDR_NODE_NAME} port=5432 dbname=${PG_DATABASE} user=postgres password=${PG_POSTGRES_PASSWORD}}

pg_ctl() {
	as_postgres "${PGBIN}/pg_ctl $(printf '%q ' "$@") -D '$PGDATA'"
}

as_postgres() {
	su postgres -- -c "$@"
}

psql() {
	as_postgres "${PGBIN}/psql '$PG_DATABASE' $(printf '%q ' "$@")"
}

psql_no_db() {
	as_postgres "${PGBIN}/psql $(printf '%q ' "$@")"
}

init_pgdata() {
if as_postgres ! [ -f "${PGDATA}/PG_VERSION" ] ; then
		echo "Initializing ${PGDATA}"
		as_postgres "${PGBIN}/initdb -A reject --locale en_US.UTF-8 --encoding=UTF-8 -D $PGDATA"
		
		echo "ALTER ROLE postgres PASSWORD '$(printf %q "$PG_POSTGRES_PASSWORD")'" | \
		  as_postgres "$PGBIN/postgres --single -D '$PGDATA'"

		echo "CREATE DATABASE \"$(printf %q "$PG_DATABASE")\"" | \
		  as_postgres "$PGBIN/postgres --single -D '$PGDATA'"

		DID_PG_INIT=y
	fi
}

set_pg_conf() {
	local key=${1}
	local value=${2}

	if [ -n "$key" -a "$value" ]; then
		echo "Setting postgresql.conf: $key = '$value'"
		as_postgres "sed -i \"s|^#\?\(${key} =\).*$|\1 '${value}'|g\" $POSTGRESQL_CONF"
	fi
}

setup_replication() {
	if [ "$(psql -At -c "select count(*) > 0 FROM pg_catalog.pg_namespace WHERE nspname='bdr'")" != "t" ]; then
		psql -c "CREATE EXTENSION btree_gist"
		psql -c "CREATE EXTENSION bdr"
	fi

	if [ "$(psql -At -c "select count(*) FROM bdr.bdr_nodes WHERE node_name='$BDR_NODE_NAME'")" = "0" ]; then
		if [ -n "$RENDEZVOUS_DSN" ]; then
			psql -c "SELECT bdr.bdr_group_join(
			           local_node_name   := '$BDR_NODE_NAME',
			           node_external_dsn := '$EXTERNAL_DSN',
			           join_using_dsn    := '$RENDEZVOUS_DSN',
			           node_local_dsn    := 'host=/var/run/postgresql port=5432 user=postgres dbname=$PG_DATABASE'
			         )"
			psql -c "SELECT bdr.bdr_node_join_wait_for_ready()"
		else
			psql -c "SELECT bdr.bdr_group_create(
			           local_node_name   := '$BDR_NODE_NAME',
			           node_external_dsn := '$EXTERNAL_DSN',
			           node_local_dsn    := 'host=/var/run/postgresql port=5432 user=postgres dbname=$PG_DATABASE'
			         )"
		fi
	fi
}

set_pg_config() {
	# These settings are mandatory for BDR to work
	set_pg_conf max_replication_slots 10
	set_pg_conf max_wal_senders 10
	set_pg_conf shared_preload_libraries bdr
	set_pg_conf track_commit_timestamp true
	set_pg_conf wal_level logical

	# This is just plain handy
	set_pg_conf log_destination stderr
	
	# Grab all config entries from the environment
	for SETTING in $(compgen -A variable PG_CONF_); do
		echo "ENV: ${SETTING}=${!SETTING}"
		set_pg_conf ${SETTING#PG_CONF_} "${!SETTING}"
	done
}

setup_hba_config() {
	enable_ssl

	as_postgres "echo 'local   all         postgres              peer' > '$PG_HBA_CONF'"
        as_postgres "echo 'local   replication postgres              peer' >> '$PG_HBA_CONF'"
        as_postgres "echo 'hostssl all         postgres all          md5'  >> '$PG_HBA_CONF'"
        as_postgres "echo 'hostssl replication postgres all          md5'  >> '$PG_HBA_CONF'"

	as_postgres "echo '$HBA_CONFIG' >> '$PG_HBA_CONF'"
}

enable_ssl() {
	set_pg_conf ssl on
	
	if as_postgres ! [ -e "${PGDATA}/server.key" ]; then
        as_postgres "openssl req -x509 -newkey rsa:2048 -nodes -keyout '${PGDATA}/server.key' -subj /CN='$BDR_NODE_NAME' -out '${PGDATA}/server.crt' -days 3650"
	fi
}

init_pgdata
setup_hba_config
set_pg_config

if ! [ -d "/var/run/postgresql" ]; then
	echo "Creating /var/run/postgresql"
	chmod 777  /var/run
	as_postgres "mkdir -p /var/run/postgresql"
fi


unset -v PG_POSTGRES_PASSWORD

pg_ctl -w start

if [ "$DID_PG_INIT" = "y" ] && [ -n "$SYSTEM_SQL_FILE" ]; then
	psql_no_db < "$SYSTEM_SQL_FILE"
fi

if [ -n "$WAIT_FOR_ROLE" ]; then
	while [ "$(psql -At -c "select count(*) > 0 FROM pg_authid WHERE rolname = '$WAIT_FOR_ROLE'")" != "t" ]; do
		echo "Waiting for user $WAIT_FOR_ROLE to exist before replicating" >&2
		sleep 1
	done
	sleep 2
fi

setup_replication

if [ "$DID_PG_INIT" = "y" ] && [ -z "$RENDEZVOUS_DSN" ] && [ -n "$DB_SQL_FILE" ]; then
	while [ "$(psql -At -c "select count(*) > 1 FROM bdr.bdr_nodes WHERE node_status='r'")" != "t" ]; do
		echo "Waiting for BDR to be running before running schema" >&2
		sleep 5
	done
	psql < "$DB_SQL_FILE"
fi

while true; do
	sleep 86400 &
	wait $! || true

	if ! pg_ctl status >/dev/null 2>&1; then
		echo "PostgreSQL terminated."
		exit 0
	fi
done

echo "CAN'T HAPPEN: DROPPED OUT OF INFINITE LOOP" >&2
exit 42
